### ISSUE TITLE
Why Nikhil Sharma is an officer title? 

### ISSUE THREAD

**Issue by johnny-y-wang** [HarkerDev/harker-hacks#3]
Dear Harker Hack Administration, 

I was recently browsing the HarkerHacks site, and it came to my attention that `Nikhil Sharma` was listed as the official title of Rohan Sonecha. According to `git blame`, @DJMcoder is responsible for this commit, who is not on the official team roster either. 

Is this an accidental mistake made by external contractors, or `Nikhil Sharma` is an actual officer title? 

Thanks,
Johnny 

--- 
Att: line affected

https://github.com/HarkerDev/harker-hacks/blob/c9da0f1b9a30c1e0da66a6eb031569212ce725f3/team.html#L69

**Comment by cameronus** [comment]
+1 @DJMcoder Can confirm that this is still an issue. Please fix this as soon as possible, since this website is publicly available at this time.

Sincerely,
Cameron

**Comment by Vedaad-Shakib** [comment]
Hi all,

I applied to join Harker Dev a month or so back--have not gotten a response. Can anyone tell me what the current status of my application is?

Sincerely,
Vedaad

**Comment by johnny-y-wang** [comment]
@Vedaad-Shakib I would defer your specific application status to @DJMCoder. If you are rejected, you are welcome to apply to H-Crypt, another student developer group here at Harker who notably runs the election. We will release application

**Comment by nakulbajaj** [comment]
I will remember this issue for the rest of my life.

Never knew git could be so fun...

**Comment by Vedaad-Shakib** [comment]
@DJMcoder could you please comment on my application status?

@johnny-y-wang when will the application come out and where will it be accessible?

**Comment by johnny-y-wang** [comment]
@Vedaad-Shakib Actually we are still waiting on our third-party contractor HarkerDev to develop their HarkerApply system so that our applicants can check 500 boxes to demonstrate their technical ability. 

If they don’t get it done by June, we will just use a Google Form. So keep an eye on your email :)

**Comment by Andrew-Tierno** [comment]
@Vedaad-Shakib I too have not been hearing back from my application! Is there some funny business going on here? I have half a mind to write a strongly worded email to the folks at HarkerDev.
@DJMcoder I invested a substantial amount of time clicking all of those 400 boxes so I believe I have successfully demonstrated my box clicking prowess! What more do I need to be "one of the team"?

**Comment by mananshah99** [comment]
Always on your side @Vedaad-Shakib ;)
